# Generated by Selenium IDE
"""
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTestchatinterfaceuploaddocumentlogout():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_testchatinterfaceuploaddocumentlogout(self):
    self.driver.get("http://localhost:3000/")
    self.driver.set_window_size(1050, 892)
    self.driver.find_element(By.CSS_SELECTOR, ".sign-in-text").click()
    self.driver.find_element(By.CSS_SELECTOR, ".maximise-icon").click()
    self.driver.find_element(By.CSS_SELECTOR, ".message-input").click()
    self.driver.find_element(By.CSS_SELECTOR, ".message-input").send_keys("Hello! I need your help today.")
    self.driver.find_element(By.CSS_SELECTOR, ".send-button:nth-child(1)").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".send-button:nth-child(1)")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".input-area > .file-upload-label path").click()
    self.driver.find_element(By.CSS_SELECTOR, ".folder-item:nth-child(2) .file-type-icon").click()
    self.driver.find_element(By.CSS_SELECTOR, ".ok-button").click()
    self.driver.find_element(By.CSS_SELECTOR, ".message-input").click()
    self.driver.find_element(By.CSS_SELECTOR, ".message-input").send_keys("What are the contents of the document?")
    self.driver.find_element(By.CSS_SELECTOR, ".send-button:nth-child(1) path:nth-child(2)").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".send-button:nth-child(1) path:nth-child(2)")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, ".message-list")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).click_and_hold().perform()
    element = self.driver.find_element(By.CSS_SELECTOR, ".message-list")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, ".message-list")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
    self.driver.find_element(By.CSS_SELECTOR, ".close-button").click()
    self.driver.find_element(By.CSS_SELECTOR, ".profile-icon").click()
    self.driver.find_element(By.CSS_SELECTOR, ".profile-dropdown > button").click() 
"""