# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestMovefileselenium():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_movefileselenium(self):
    self.driver.get("http://localhost:3000/")
    self.driver.set_window_size(1050, 892)
    self.driver.find_element(By.CSS_SELECTOR, ".sign-in-text").click()
    self.driver.find_element(By.CSS_SELECTOR, ".yAlK0b").click()
    self.driver.find_element(By.CSS_SELECTOR, ".ksBjEc > .VfPpkd-vQzf8d").click()
    self.driver.find_element(By.CSS_SELECTOR, ".VfPpkd-ksKsZd-mWPk3d-OWXEXe-Tv8l5d-lJfZMc > .VfPpkd-vQzf8d").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".tyoyWc .VfPpkd-vQzf8d")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.ID, "i1").click()
    self.driver.find_element(By.CSS_SELECTOR, ".VfPpkd-ksKsZd-mWPk3d-OWXEXe-Tv8l5d-lJfZMc > .VfPpkd-RLmnJb").click()
    element = self.driver.find_element(By.CSS_SELECTOR, "#submit_approve_access .VfPpkd-RLmnJb")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".file-item:nth-child(1) .more-options > .MuiSvgIcon-root").click()
    self.driver.find_element(By.CSS_SELECTOR, ".action-button:nth-child(4) > .MuiSvgIcon-root").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".action-button:nth-child(4) > .MuiSvgIcon-root")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".folder-item:nth-child(5)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".ok-button").click()
    self.driver.find_element(By.CSS_SELECTOR, ".profile-icon > path").click()
    self.driver.find_element(By.CSS_SELECTOR, ".clickable").click()
  
