'''
# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestNewfoldercreationselenium():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_newfoldercreationselenium(self):
    self.driver.get("http://localhost:3000/drive")
    self.driver.set_window_size(1050, 892)
    self.driver.find_element(By.CSS_SELECTOR, ".new-item-button").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".new-item-button")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.CSS_SELECTOR, "button:nth-child(1) > .dropdown-menu-text").click()
    self.driver.find_element(By.CSS_SELECTOR, ".popup-input").click()
    self.driver.find_element(By.CSS_SELECTOR, ".popup-input").send_keys("Demo")
    self.driver.find_element(By.CSS_SELECTOR, ".ok-button").click()
''' 
