# Use an official Node.js image as the base
FROM node:14

# Set the working directory inside the container
WORKDIR /frontend

# Copy the package.json and package-lock.json files to the container
COPY package.json package-lock.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code to the container
COPY . .

# Run Jest tests after all code is copied
RUN npm test

# Build the application
RUN npm run build

# Expose port 3000 for the application
EXPOSE 3000

# Run the application
CMD ["npm", "start"]
