services:
  backend:
    env_file:
      - ./backend/.env
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        - PINECONE_API_KEY
        - PINECONE_ENVIRONMENT
        - PINECONE_INDEX_NAME
        - OPENAI_API_KEY
    ports:
      - "8080:8080"
    environment:
      - FLASK_ENV=development
      - PYTHONPATH=/backend
      - REDIS_TOKEN_URL=redis://redis:6379/2 
    volumes:
      - ./backend:/backend
    depends_on:
      - redis
    command: sh /backend/start.sh
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
      
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development