services:
  backend:
    env_file:
      - ./backend/.env
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        - PINECONE_API_KEY
        - PINECONE_ENVIRONMENT
        - PINECONE_INDEX_NAME
        - OPENAI_API_KEY
        - REDIS_TOKEN_URL=rediss://diganise-redis:6378
    ports:
      - "8080:8080"
    environment:
      - FLASK_ENV=development
      - PYTHONPATH=/backend
    volumes:
      - ./backend:/backend
    command: sh /backend/start.sh

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development