# Build frontend
FROM node:14 AS frontend-build
WORKDIR /frontend
COPY frontend/package.json frontend/package-lock.json ./
RUN npm install
COPY frontend .
RUN npm run build

# Build backend
FROM python:3.10-slim
WORKDIR /app

# Copy backend files
COPY backend/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY backend .

# Copy built frontend files
COPY --from=frontend-build /frontend/build /app/static

EXPOSE 8080

CMD ["gunicorn", "-b", "0.0.0.0:8080", "app:app"]