# Use an official Python runtime as a parent image
FROM python:3.12

# Set the working directory in the container
WORKDIR /backend

# Copy the requirements file into the container
COPY requirements.txt .

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copy the entire backend directory into the container
COPY . .

# Make port 8080 available to the world outside this container
EXPOSE 8080

# Set the Python path to include the current directory
ENV PYTHONPATH=/backend:$PYTHONPATH

# Set environment variables
ARG PINECONE_API_KEY
ARG PINECONE_ENVIRONMENT
ARG PINECONE_INDEX_NAME
ARG OPENAI_API_KEY

ENV PINECONE_API_KEY=$PINECONE_API_KEY
ENV PINECONE_ENVIRONMENT=$PINECONE_ENVIRONMENT
ENV PINECONE_INDEX_NAME=$PINECONE_INDEX_NAME
ENV OPENAI_API_KEY=$OPENAI_API_KEY

# Run the application using Gunicorn
CMD ["gunicorn", "--bind", "0.0.0.0:8080", "wsgi:application"]