from marshmallow import Schema, fields

class DocumentSchema(Schema):
    id = fields.Str(required=True)
    googleDriveId = fields.Str(required=True)
    title = fields.Str(required=True)
    mimeType = fields.Str(required=True)
    createdAt = fields.DateTime(required=True)
    modifiedAt = fields.DateTime(required=True)
    ownerId = fields.Str(required=True)
    parentFolderId = fields.Str()
    aiSuggestedCategories = fields.List(fields.Str())
    userCategories = fields.List(fields.Str())
    suggestedFolder = fields.Str()
    userSelectedFolder = fields.Str()
    metadata = fields.Dict()
    summary = fields.Str()
    keywords = fields.List(fields.Str())
    lastEmbeddingUpdate = fields.DateTime()
    version = fields.Int()
    accessControl = fields.Dict()
    sharedFolders = fields.List(fields.Str())
    sourceUrl = fields.Str()
    citations = fields.List(fields.Str())
    languageCode = fields.Str()
    webViewLink = fields.Str()
    lastSyncTime = fields.DateTime()
    chunk_index = fields.Int()
    total_chunks = fields.Int()